### ISSUE TITLE
Nesting

### ISSUE THREAD

**Issue by servant74** [openhardwarecoza/LaserWeb#106]
I ran across http://svgnest.com/

It is an open source nesting solution that should allow getting more out of sheet stock.  It is missing a small thing or so, like 'required orientation' that would allow consistent 'grain' in some required parts (think making wood match, also important on patterned material of other kinds).

Still, if someone that is more of a programmer than I am could make this an enhancement or seamless addin, it could some some folks lots of material.

Thanks for the consideration.

**Comment by ghost** [comment]
Discussed at length here https://plus.google.com/+ArthurWolf/posts/eVxYxnQCiHp and https://github.com/openhardwarecoza/LaserWeb/issues/86 (: 

Long story short. Not easy  :(
