### ISSUE TITLE
Add SVG edit and vectorising

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb#107]
Possible solutions

SVG edit
https://github.com/SVG-Edit/svgedit

Vectorizing
https://github.com/jankovicsandras/imagetracerjs

Nesting
https://github.com/Jack000/SVGnest (I see you reached to jack)

**Comment by ghost** [comment]
Closing this for now - threejs is too integral and none of this integrates nicely. Sebastien is working on a packing algorith for threejs by they way (;
