### ISSUE TITLE
svg widget generates slow moves between cut paths

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb#109]
The moves between cut and cut are very slow, seems like those Z F200 and F300 are crossing over the travel move somehow
<img width="1839" alt="screen shot 2016-02-18 at 9 37 30 pm" src="https://cloud.githubusercontent.com/assets/16444438/13165121/39cc606c-d688-11e5-8a7d-1b328e066596.png">
[Skull-0.eps-LaserWeb.gcode.txt](https://github.com/openhardwarecoza/LaserWeb/files/137347/Skull-0.eps-LaserWeb.gcode.txt)

**Comment by ghost** [comment]
Sorry about the 9 day delay - was in Hardware Mode last week! 

Fixed - do a git pull (:
