### ISSUE TITLE
Chrome crashes while loading gcode files

### ISSUE THREAD

**Issue by funinthefalls** [openhardwarecoza/LaserWeb#11]
Any time I try to bring a gcode file into laserweb, the chrome browser page crashes. Does not happen with dfx or svg files, however laserweb does not output anything that resembles the original dfx file.

**Comment by ghost** [comment]
DXF:  Make sure its Polyline DXFs (Not Lines or Polymesh)
A quick open and resave in QCad as DXFv15 helps sometimes too.

GCODE: Upload some example code, and I'll take a look (google drive, dropbox or pastebin)

In both cases, looking at the Developer Console in chrome helps too (logging errors to console)
(Ctrl+Shift+I)

**Comment by ghost** [comment]
No feedback from user. Closing Issue
