### ISSUE TITLE
Raster strange engraving paths

### ISSUE THREAD

**Issue by nextime** [openhardwarecoza/LaserWeb#113]
Hello,
i'm trying to rasterize some images, and then engraving them, but i get unexpected results.

On the 3d view it seems ok, but when i engrave it, there are some paths added.

Any idea on why does that? i'm not sure if it's a bug or something i'm doing wrong...

![rasky-640](https://cloud.githubusercontent.com/assets/3410003/13250567/0221726e-da2b-11e5-9a32-10ad1d73e0a9.jpg)

![img_20160223_123904](https://cloud.githubusercontent.com/assets/3410003/13250601/39875926-da2b-11e5-9c5a-85a8c8387fcb.jpg)

**Comment by ghost** [comment]
Which firmware are you using?  Looks like the grbl bug.   If its marlin,
print from SD

**Comment by nextime** [comment]
It's marlin, i don't have any sd attached :|

**Comment by nextime** [comment]
So, do you think it can be something related to how laserweb send gcode? 

Maybe i can try to send it by using pronterface...

**Comment by nextime** [comment]
Confirmed, using pronterface to send gcode it works like a charm, so, it seems to be an issue with the serial implementation in laserweb/node.js?

**Comment by ghost** [comment]
Marlin cant keep its serial buffer full.. Upgrade to a smoothie or add an
SD Card

**Comment by ghost** [comment]
Also,  see the other open issues here

**Comment by nextime** [comment]
I don't think it's a marlin issue as using another host ( pronterface ) the issue disappear, seems more between node.js and serial

**Comment by ghost** [comment]
Thats why i say,  look at the other open issues here...  Instead of opening
a duplicate to argue  (;

**Comment by ghost** [comment]
See

https://github.com/openhardwarecoza/LaserWeb/issues/94  

And here where i escalated to node-serialport 

https://github.com/voodootikigod/node-serialport/issues/663

And this (just one of several posts on the matter on g+) 

The past week worth of work busy porting to chilipeppr
https://plus.google.com/+PetervanderWalt/posts/19Qz4QowESa

A whole community
https://www.google.co.za/url?sa=t&source=web&rct=j&url=https://plus.google.com/communities/118113483589382049502&ved=0ahUKEwjtgLGukI7LAhUC1hQKHRQGCnIQFggYMAA&usg=AFQjCNEZwbWNPiy0I7Jh525hnMYD81dxRA&sig2=sxjco0bEOSrX8rGyA5CJQQ

Yet,  you rather user your effort to complain than to contribute  (;

**Comment by nextime** [comment]
sorry if it seems to be a complain, it isn't really, probably a language barrier ( i'm not native english ), but i was just trying to understand and investigate to eventually, if i will be able to, even contribute with patches.

Thanks anyway for your pointers

**Comment by ghost** [comment]
(: cool.  Goodluck!
