### ISSUE TITLE
"Send to laser" not working.

### ISSUE THREAD

**Issue by Dikabro** [openhardwarecoza/LaserWeb#114]
Hello.
I'm trying to launch my GRBL v08c laser cnc on LaserWeb. It seems that everything works except "Send to laser" functionality. When I press this button in console I see text:
"SEND: G21
SEND: G90
SEND: G1 F280
error: Invalid statement
Aborted Job!  Safety First!"
:/

**Comment by ghost** [comment]
Duplicate,  see the open ticket on the issues page about Grbl Resends

See

https://github.com/openhardwarecoza/LaserWeb/issues/94  

And here where i escalated to node-serialport 

https://github.com/voodootikigod/node-serialport/issues/663

**Comment by ghost** [comment]
Or upgrade to a smoothieware based controller - well worth the spend
