### ISSUE TITLE
Running on lasersaur (direct on beaglebone)

### ISSUE THREAD

**Issue by Powerscripter** [openhardwarecoza/LaserWeb#117]
Hi,
I try to run the Server directly on the beaglebone of my lasersaur.
node JS and Laserweb are running well but it does not find the Lasersaur.
I added ttyO1 to the ports as this is the saur Port.
After disconnecting the lasersaur´s web Interface LAserweb Server logs:
WARN: Ignored:  Port /dev/ttyO1 said:  E
After restarting the atmega it logs:
WARN: Ignored:  Port /dev/ttyO1 said:  #035; LasaurGrbl 14.11
But it still not works.
Is there a way to run it on Beagle bone?
Thank you martin

**Comment by ghost** [comment]
Are you sure you properly shutdown the Lasaurapp processes?  They might be holding the port open
