### ISSUE TITLE
Marlin gcode generated

### ISSUE THREAD

**Issue by luismanson** [openhardwarecoza/LaserWeb#119]
Hi, first of all, great software. I might be doing al wrong here so before even saying my problem i will show my current setup
I just bought a chinese 2W  module with a TTL input in the driver for my Prusa i3 (with marlin), 
i ignored this and put the 12v input to D9 (second extruder) which i use with PWM (M106 Sxxx)
 in machine setting of laser web i edited laser on and off options to use M106 / M107. however the generated code is alway like "G1 X0.0 Y13.8 S45"

is this a but, its ignoring my profile or what?

**Comment by ghost** [comment]
Use TurnkeyTyranny's Marlin for Lasers.  It doesnt use m codes.  It burns
on G1 and doesnt burn on G0 moves.

Also checkout LaserWeb2 (early beta) which allows you to configure what you want to use (the functionality is working in LaserWeb2 but as you can see from LaserWeb1's open issues tab https://github.com/openhardwarecoza/LaserWeb/issues/7 is still open).  My last comment there was "What I am not doing yet is to use https://github.com/openhardwarecoza/LaserWeb/blob/master/i/main.js#L413 to set the variables we need to use elsewhere (start, stop gcode, laser on off and power commands, bed size, etc)"

Always check open issues before opening new ones (;
