### ISSUE TITLE
Improve windows installation docs

### ISSUE THREAD

**Issue by tealvince** [openhardwarecoza/LaserWeb#121]
Suggest:

1) when installing node.js, indicate that the .msi file is the one to install of the list of files displayed.
2) when downloading laserweb, using the zip file is probably easier and more familar to Windows users than git.

**Comment by funinthefalls** [comment]
Tealvince, please go ahead and write up what you think the users would understand, post it here as a comment, and I will try to integrate it into the install instructions. Thanks for your feedback.

**Comment by ghost** [comment]
Downloading the zip, breaks future update -- inside nodejs we call git pulls later to automate updates so its CRITICAL the user sets up a working Git SCM install!!!  NB NB
