### ISSUE TITLE
Cannot find serial port under WinXP

### ISSUE THREAD

**Issue by tealvince** [openhardwarecoza/LaserWeb#122]
On my old laptop running Windows XP, two serial ports are available in Pronterface, COM3 and COM5.  COM5 is the correct port.  LaserWeb displays COM3 as the only choice.  Not sure if this is covered by issue #21.

**Comment by ghost** [comment]
I doubt xp is properly supported by node-serialport.

Try LaserWeb2 which uses spjs.
