### ISSUE TITLE
Resolved - LaserWeb on RaspberryPi

### ISSUE THREAD

**Issue by LordFennec** [openhardwarecoza/LaserWeb#13]
Hi at all. After many tests I was able to perform laserweb of RaspberryPi (raspberryPi 2 with jessie OS).
Apparently there are version incompatibility with serialport and node. I'm not a programmer and expert linux but I managed to do it all work.
Following the instructions for ubuntu version, when I arrived in "cd LaserWeb" I followed the next steps.
-Run everything below as root (su)
-Install build tools (apt-get install python g++ make)
-Install node.js for Raspberry Pi with this script: https://github.com/midnightcodr/rpi_node_install
-npm install serialport@1.6.1
-npm install socket.io node-static

Finally launch the service with 
-node serever.js

I do not know if it is the most correct procedure but it works

**Comment by ghost** [comment]
Thank you @LordFennec !  Added to readme https://github.com/openhardwarecoza/LaserWeb/commit/920c185c7ce73fc5f2c29aa54e0265c10069499a
