### ISSUE TITLE
Formatting on mobile

### ISSUE THREAD

**Issue by adeebshihadeh** [openhardwarecoza/LaserWeb#2]
The page works wonderfully on mobile. The gcode preview works with dragging and pinch to zoom. However, the formatting isn't quite there. 
![image](https://cloud.githubusercontent.com/assets/8762862/11054369/108d7338-8720-11e5-8277-361e033108b8.png)

**Comment by ghost** [comment]
Indeed I am aware of that.  I am not using a responsive layout (i was lazy and used two absolute <divs> left and right divs   I also still need to squeeze in the Webcam widget and CAM components, so screen real estate might be getting tight.   On my build of reprapweb I hide the less often used things in Modals that pop out from buttons. Will probably do the same here

**Comment by ghost** [comment]
![modal](https://cloud.githubusercontent.com/assets/7695323/11057625/562238a0-8795-11e5-9292-96953f8b6dea.PNG)

@quillford, give this one a go on your tablet?  Moved the jog to a widget - plenty of space for macro buttons and the like where your motor button is

https://github.com/openhardwarecoza/LaserWeb/commit/623ad62ac55ce47e485edf933c04dcde1ccdbbf1

**Comment by ghost** [comment]
Fixed a bug.  Machine Control button should be disabled until a port is selected

https://github.com/openhardwarecoza/LaserWeb/commit/2d1ad4a2570646e2b667c5eefef4486d27f585e5

**Comment by ghost** [comment]
Oops accidentally clicked close.

This morning I upgraded to bootstrap 3.3.5 (from 3.1.1) and changed to a responsive layout with standard bootstrap formatting (no absolute divs)

Works on my Galaxy S5 and PC/ Please test on tablet etc and revert with comments
