### ISSUE TITLE
Using M03 S#### for pwm the laser

### ISSUE THREAD

**Issue by Cinezaster** [openhardwarecoza/LaserWeb#24]
grbl supports variable spindle speeds.
I pwm my laser output with the spindle speed.
This is use full for engraving different materials.
Grbl is not optimized for changing spindle speeds while moving. Because in a mill type CNC operation you wouldn't change spindle speed while moving. But still a use full feature.

**Comment by ghost** [comment]
See https://github.com/openhardwarecoza/LaserWeb/issues/23
