### ISSUE TITLE
rpi install does not work

### ISSUE THREAD

**Issue by Kenzu** [openhardwarecoza/LaserWeb#26]
Can't get it to run.
Gives me this error
{ [Error: ENOENT, no such file or directory '.env'] errno: -2, code: 'ENOENT', path: '.env', syscall: 'open' }
Error connecting to webcam: connect ECONNREFUSED - Disabling Webcam Widget
/home/pi/LaserWeb/server.js:89
        ports.push({comName:'/dev/ttyAMA0',manufacturer: Broadcom,pnpId: 'raspberr
                                                         ^
ReferenceError: Broadcom is not defined
    at /home/pi/LaserWeb/server.js:89:54
    at /home/pi/LaserWeb/node_modules/serialport/node_modules/async/lib/async.js:254:17
    at done (/home/pi/LaserWeb/node_modules/serialport/node_modules/async/lib/async.js:135:19)
    at /home/pi/LaserWeb/node_modules/serialport/node_modules/async/lib/async.js:32:16
    at /home/pi/LaserWeb/node_modules/serialport/node_modules/async/lib/async.js:251:21
    at udev_parser (/home/pi/LaserWeb/node_modules/serialport/serialport.js:512:7)
    at /home/pi/LaserWeb/node_modules/serialport/serialport.js:554:13
    at ChildProcess.exithandler (child_process.js:742:7)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)

**Comment by ghost** [comment]
Oops, little typo, two missing '' in 

https://github.com/openhardwarecoza/LaserWeb/commit/fd146c2a61db98809f360c07ee8d7282f03d82ff#diff-78c12f5adc1848d13b1c6f07055d996eR89

Fixed now, git pull, then try again

**Comment by Kenzu** [comment]
Thanks :-)
