### ISSUE TITLE
Hangs on connecting to Laser Cutter/Engraver serial port.

### ISSUE THREAD

**Issue by funinthefalls** [openhardwarecoza/LaserWeb#28]
The LaseWeb software appears to hang when trying to connect to Laser Cutter/Engraver serial port. It jus sits there, have waited as long as 1/2 to connect but no success.

**Comment by ghost** [comment]
Can you give me more details on your setup? 

Os
Board 
Firmware? 

Etc

**Comment by funinthefalls** [comment]
OS: Windows 10
Board Ramps 1.4/Arduino Mega2560 with RepRap full graphic LCD
Firmware: most recent build of Turnkey Tyranny's Marlin
GCode creation: Inkscape---->Turnkey Tyranny's Laser Exporter (for both vector and raster) --->Pronterface = Success
GCode creation: Inkscape---->Turnkey Tyranny's Laser Exporter (for both vector and raster) --->Laserweb = Failure to connect

This is running on a 6 core AMD phenom with 16GB Ram, 1 GB video card

**Comment by ghost** [comment]
Screenshot of node terminal showing the hang?

**Comment by ghost** [comment]
Other mental checks:

NB: do a 'git pull' in the LaserWeb directory to make sure you get the latest code
1.  Make sure board is plugged in before starting laserweb
2.  Make sure pronterface is NOT still open (else it would hold on to the port)
3.  You should see the terminal do something like this
   ![terminal](https://cloud.githubusercontent.com/assets/7695323/12008969/ef40967a-ac6c-11e5-95b3-2bf320c4bd1a.png)

Note that if you get that far and the fact that nothing else prints on the terminal, is what you consider a HANG, it means you havent read the readme (https://github.com/openhardwarecoza/LaserWeb/blob/master/README.md#access)

After starting laserweb, you need to open a web browser to http://127.0.0.1:8000 (or http://ip-of-your-server:8000)

![browser](https://cloud.githubusercontent.com/assets/7695323/12008976/49aeb862-ac6d-11e5-8bd2-e30638f61731.png)

**Comment by ghost** [comment]
I have updated server.js to print you a message with instructions on where to go next:
![terminal](https://cloud.githubusercontent.com/assets/7695323/12009122/da077a9c-ac73-11e5-8f1e-fbbf11e53bd8.png)

And I have also updated the README:  See  https://github.com/openhardwarecoza/LaserWeb#access-instructions
