### ISSUE TITLE
Webcam / Red Dot (Fiducial) Layout Rotation

### ISSUE THREAD

**Issue by iceblu3710** [openhardwarecoza/LaserWeb#33]
My #1 complaint with my current laser is aligning things is a PITA. I currently put alignment marks on multi cut pieces and need to pin and pivot the piece to keep everything aligned. It would be super helpful if I could jog the machine to (point1) and select that location on the drawing then jog to (point2) and select that in the drawing and the software would rotate the whole drawing to match.

Another feature would be to have a webcam facing towards the workpiece on the X/Y carriage and capture a video scanning the entire printable area. Then stitching it together and showing it as the background. This could then be used for the feature above but would not require any feedback for position info.

**Comment by ghost** [comment]
I like the alignment idea.  Fiducial Marks as its called,  my vinyl cutter uses that to line up preprinted prints for cutting...  Keeping this open (:

**Comment by martinxyz** [comment]
In our fablab we have two fixed red lasers projecting a line on the X and Y axes of the bed/workpiece. Alignment has become so easy that it's a non-issue - it feels like cheating.

**Comment by iceblu3710** [comment]
The problem is when you need to align a piece in two axis. Currently i align the piece lower left to a mark and zero the lazer. Then in Corel Draw i need to take the (x, y) offset from that corner to the upper right marker. I then move the laser back/forth to get both locations under the alignment laser.

Takes 10x longer to align than cut.

**Comment by ghost** [comment]
@johnlauer is going something similar in Chilipeppr - where he uses the camera widget to view the fiducials, then wants to scale and rotate the code to match  the actual PCB angle/size.   We may be able to share some workload

**Comment by ghost** [comment]
I'll close this one for now (:
