### ISSUE TITLE
Scale, Rotate, Move, Bounding Box errors

### ISSUE THREAD

**Issue by funinthefalls** [openhardwarecoza/LaserWeb#38]
The entry boxes for scale and rotate do not display any values typed into them. Bounding B0x button appears to do nothing. Move entry boxes only display one digit (45 will display as 5). Move on the X axis appears to move 10X the entered value i.e. enter 20 and it moves 200.

**Comment by funinthefalls** [comment]
Update....increased my screen resolution to 1600X900 on a 32" Samsung monitor....now displays all entry boxes and buttons correctly. Only problem left is that the bounding box button appears to do nothing. Is there any way to get everything to display at a lower resolution? At 1600X900 text is very small.

**Comment by ghost** [comment]
Bounding box sends gcode to the machine (doesnt do anything onscreen)  

Are you using chrome,  i run it even on my tablet,  its not a resolution issue

**Comment by ghost** [comment]
Ok,  i managed to reproduce it on Chromium on my ubuntu Laptop

**Comment by ghost** [comment]
![scale](https://cloud.githubusercontent.com/assets/7695323/12168682/796e102a-b53c-11e5-8f44-9ffcbdc29e96.png)

@funinthefalls - I did some resizing of the objects in that area, see if this resolved it for you?

**Comment by funinthefalls** [comment]
![chrome](https://cloud.githubusercontent.com/assets/3101946/12172722/926b0b6c-b520-11e5-916a-28ee838e9200.png)
Still the same....here is a screen shot.

Date: Thu, 7 Jan 2016 02:45:29 -0800

**Comment by ghost** [comment]
I dont see the changes.  You did update?   I cant magically deploy it down to you (; 

Do a 'git pull'  in the laserweb directory

**Comment by funinthefalls** [comment]
I did update it, I deleted the previous version completely, then dis a git clone.

Date: Thu, 7 Jan 2016 07:06:15 -0800

**Comment by ghost** [comment]
Ok.  Will see how else i can shuffle it

**Comment by ghost** [comment]
![smaller](https://cloud.githubusercontent.com/assets/7695323/12223462/f62ea9e8-b7e0-11e5-8cdf-9e1e77c67610.png)
