### ISSUE TITLE
Merge in Millcrum so we can get svg ->cut and dxf-> cut

### ISSUE THREAD

**Issue by ghost** [openhardwarecoza/LaserWeb#4]
Merge in Millcrum so we can get svg ->cut and dxf-> cut

**Comment by adeebshihadeh** [comment]
Is anyone working on this? If not, I'll start working on it in my fork.

**Comment by ghost** [comment]
I actually worked on it a bit:

https://github.com/openhardwarecoza/LaserWeb/commit/1ad2ed94c9cd7a550bcfc9b4f46d25a04d1b3e0f

So far, I have working:

Open DXF (converts to millcrum and puts the millcrum code in a text area)
What I am working on still is the millcrum to dxf.  
SVG to millcrum - i added the button but havent played with the function just yet, thats next

Once both buttons get the input file to the text area (easy to change from original code) - its just a matter of doing the millcrum to gcode function.

**Comment by ghost** [comment]
Right so. I have made a bit of progress, but got stuck.  @andrewhodel my reverse engineering js skills (those ones that make you cringe, I know) has managed to get to the point where I open a file, it converts it to millcrum.  But my generate doesnt do what your generate does... 

https://github.com/openhardwarecoza/LaserWeb/blob/master/i/main.js#L363b

**Comment by andrewhodel** [comment]
Basically it runs the millcrum code in an eval and uses the try catch block to catch any errors from the eval.

If you have the millcrum code, just copy and paste it directly in the generate block and don't run the eval statement.  Then you will be able to see line numbers for the errors in the JS console and work through any problems.

All of the millcrum code runs functions in inc/mc.js

**Comment by ghost** [comment]
aha! the Eval is the key! Didnt know what it does.

Okay let the digging proceed.

**Comment by ghost** [comment]
i see so var tool is undefined, once run through the eval, tool = {units:"mm",diameter:6.35,passDepth:4,step:1,rapid:2000,plunge:100,cut:600,zClearance:5,returnHome:true};

**Comment by ghost** [comment]
You the man @andrewhodel !   Sorted and working!  https://github.com/openhardwarecoza/LaserWeb/commit/75e10ba0df23604f658d4a5f72aedcb00a403cd4

I need to do a tonne of cleanup of console.log statements i used to try to see whats going on. 
Also need to change the default tool etc. But thats easy.  Closing this issue, the remaining things are simple enhancements.

Lesson learned. eval executes the JS :|  - i should get a JS book for xmas and read it over the holidays...
