### ISSUE TITLE
Importing gcode done with Jtech inkscape pluging shows incorrect render

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb#45]
I used jtech inkscape plugin to generate the code. Its does not show correctly on the screen and the output in the laser also seems weird. Unable to determine it its correct
[met_0003.gcode.txt](https://github.com/openhardwarecoza/LaserWeb/files/78043/met_0003.gcode.txt)

<img width="1835" alt="screen shot 2016-01-05 at 12 21 20 am" src="https://cloud.githubusercontent.com/assets/16444438/12108176/867f6ad0-b342-11e5-9246-37fbe94244fc.png">

**Comment by ghost** [comment]
Theres some G2, G3, G4 etc in there.  To cater for the lowly grbl and marlin users too, its best to stick to polyline type designs (ie circles split into several shorter G1 moves, etc)
