### ISSUE TITLE
Calibration Widget

### ISSUE THREAD

**Issue by ghost** [openhardwarecoza/LaserWeb#47]
Remember when you got an Inkjet printer in the 90s, and it had you always go to do a calibration:

![14739](https://cloud.githubusercontent.com/assets/7695323/12155728/7540328e-b4cf-11e5-928b-2bf6febb0f60.jpg)

and have you print something like this

![line](https://cloud.githubusercontent.com/assets/7695323/12155736/814e273e-b4cf-11e5-8383-b6b2533deaae.png)

Whereafter you tell the driver which looked best?

I am going to add the same thing to Laserweb:
A little test engrave and test cut job that you can run, pick the best,. enter it in the UI, and it will save your presets.   I will have you be able to run it against multiple materials and save each too?

Like?

**Comment by cojarbi** [comment]
Like very mucho

**Comment by ghost** [comment]
I already drew the image to use in the calibration widget:

https://github.com/openhardwarecoza/LaserWeb/blob/master/i/raster/calibration.jpg

And we've been using it manually to tweak a few...

At the moment I was too busy putting out bugs, havent worked with any of this any further yet.  @nathanielstenzel  - we could use you here too:

Copy the Raster widget https://github.com/openhardwarecoza/LaserWeb/blob/master/i/index.html#L809 but instead of the onload bla bla, just have the image in place already, different title, and modal doesnt close (stays open (so no https://github.com/openhardwarecoza/LaserWeb/blob/master/i/main.js#L2317) , displays some advice, make it smaller so one can see 3D viewer better and copy Send to Laser button https://github.com/openhardwarecoza/LaserWeb/blob/master/i/index.html#L238 onto the Modal)

**Comment by nathanielstenzel** [comment]
https://github.com/nathanielstenzel/LaserWeb/commit/06d21422f35a1700170602fa42cc3a4e20b237c9
That is a commit that has my start of the calibration widget so far. I tried to merge in your changes. I can't seem to make everything in the widget turn on.

**Comment by ghost** [comment]
That commit has some of my commits too :|    i need to show you how to handle remote git branching so you can seperate the pull of my work,  from the commit of your work (:

All the elements on the widget (html)  has accompanied objects in main.js (jquery)

**Comment by nathanielstenzel** [comment]
I may have actually given you the wrong link. Perhaps a slightly earlier commit of mine would have not had your changes in it. https://github.com/nathanielstenzel/LaserWeb/commit/2e3af070eaa5a37d73a7b2588b7527f81cdafe92

**Comment by nathanielstenzel** [comment]
Yep. There you go. That one is all me. I need to get your new layout in there though.

**Comment by nathanielstenzel** [comment]
https://github.com/nathanielstenzel/LaserWeb/commit/a983e0ea6ded08e923e0685ccfd48fe6aca5c324
That does not have your change in design of the button layout for the upper left, but it works. The calibration is done by the main raster widget. The code was not exactly reusable, so I just expanded it with hidden stuff. It has the side effect of the raster widget being centered. Feel free to change that. Next up would be to add other slide bars for speed vs darkness calibration. That is another chapter though.

**Comment by nathanielstenzel** [comment]
![laserweb-x1](https://cloud.githubusercontent.com/assets/9649344/12285097/2495e0f2-b97c-11e5-9c11-090d87cc14c5.png)

**Comment by nathanielstenzel** [comment]
And yes, I know you want the title changed. I just don't know how I want to go about doing that. I decided it was easier for me to expand the raster widget than make a new widget.

**Comment by nathanielstenzel** [comment]
https://github.com/nathanielstenzel/LaserWeb/commit/385d98b22acff5186ce60c6fa791e519c90e7efc The Raster widget title now differs for the image mode and the calibration mode.

**Comment by ghost** [comment]
Ok, let me try and cherry pick from your commits (: 

Else I'll do copy paste and attribute lol

**Comment by ghost** [comment]
I had to go manual :) not even cherry pick worked
Luckilly it wasnt a lot of code to find.

I did however not use the dropdown - file button in a bootstrap dropdown looks a litle weird sadly :(

**Comment by nathanielstenzel** [comment]
Got a screen shot?  You have me curious about how it looks and I will not be home for 5 hours.

**Comment by ghost** [comment]
![laserweb](https://cloud.githubusercontent.com/assets/7695323/12306149/0af3be06-ba41-11e5-9ac4-38b208457ba7.png)

**Comment by nathanielstenzel** [comment]
I meant the button that gets you to the raster calibration mode.

**Comment by ghost** [comment]
Top left

**Comment by nathanielstenzel** [comment]
Okay.  I see it.  Will that calibrate all laser output then?

**Comment by nathanielstenzel** [comment]
The send to laser button should be locked when you open the window, but it seems I don't relock it when the window opens or you click the raster button. Two bugs for me to squash in my modification.

I will try to work on that in about 19 hours.

**Comment by nathanielstenzel** [comment]
https://github.com/openhardwarecoza/LaserWeb/pull/56 That should squish those 2 bugs.

**Comment by nathanielstenzel** [comment]
https://github.com/nathanielstenzel/LaserWeb/commit/177d2415f0570b2df6a7bf223a23f9801ca8ed0f should fix that bug.

**Comment by nathanielstenzel** [comment]
You mentioned an interest in variable speeds for darknees control. How does this look?
![laserweb-x3](https://cloud.githubusercontent.com/assets/9649344/12370963/fcec0dfe-bbe9-11e5-9685-e3ea65b85d5c.png)

**Comment by ghost** [comment]
Looks good!

**Comment by nathanielstenzel** [comment]
This is now ready for testing.
