### ISSUE TITLE
The upper left is cramped and the file icon does nothing?

### ISSUE THREAD

**Issue by nathanielstenzel** [openhardwarecoza/LaserWeb#53]
After the SVG button was added, the RASTER and the GCODE buttons got cramped and not all of the letters are visible.

**Comment by ghost** [comment]
(: Buy a 1080p monitor (;

Just kidding - I'll have to make a plan there... The file icon is just  visual indicator that the ones to right means Open ... gcode, Open....svg, etc

**Comment by ghost** [comment]
![screenshot from 2016-01-12 10-37-49](https://cloud.githubusercontent.com/assets/7695323/12258689/1a28ff2c-b919-11e5-8fff-d0fef889bde5.png)

Fixed 

(the STL(Soon)button is a mockup - coming soon something, may be stl may be something else, but same number of buttons in both rows just look so much better.  Hey we can put Calibration there?

**Comment by nathanielstenzel** [comment]
I was going to have the calibration button be a drop down of the Raster like there is a drop down of the JSCAD. In fact, I already have the change committed to my branch, but I have to pull in your new layout and merge the changes into my branch.
