### ISSUE TITLE
The scroll bar on the right follows popup windows.

### ISSUE THREAD

**Issue by nathanielstenzel** [openhardwarecoza/LaserWeb#55]
It does not seem to matter what type of file you open, if you get a pop up window, the scroll bar on the right will follow the pop up window. That means that it might hide out of sight until you move your pop up window to the left some. The scroll bar will keep a consistent distance from the pop up window.

**Comment by ghost** [comment]
Can you show me a screenshot annotated with where you mean exactly?  I tried with a small screen resolution, then on 1080p and neither here shows up as a clear issue?

**Comment by nathanielstenzel** [comment]
![laserweb-x2](https://cloud.githubusercontent.com/assets/9649344/12341389/e015bc56-bae6-11e5-92fc-01ef65c3738e.png)

**Comment by nathanielstenzel** [comment]
That bar should be on the right, but since I dragged the pop up window, it is on top of the grid.

**Comment by ghost** [comment]
Ok, i can replicate. will see why that is

**Comment by ghost** [comment]
Tried a few things, but doesnt seem to be our side.

See if you can get it isolated into a JSFiddle then open a bug here https://bugs.jqueryui.com/newticket

**Comment by nathanielstenzel** [comment]
Fixed in https://github.com/nathanielstenzel/LaserWeb/commit/d1dda5b6d35bcc9745110454c15bf936f9e3ffa0 courtesy of some code copied from wellwind which published an example at https://gist.github.com/wellwind/a5a10222ad691d72a11c
