### ISSUE TITLE
Updated install instructions for Windows users

### ISSUE THREAD

**Issue by funinthefalls** [openhardwarecoza/LaserWeb#58]
Here is a step by step install for windows users:

Prerequisites:

1.Download and install Node.js version node-v0.12.7 from https://nodejs.org/download/release/v0.12.7/
2. Install Google Chrome if not already installed

LaserWeb install instructions:
1. Download the ZIP file from https://www.github.com/openhardwarecoza/laserweb
2. Unzip the file to c:\laserweb
3. Start a windows command prompt by typing cmd in the search box a t the bottom of the windows desktop screen
4. At the command prompt type "cd\laserweb"  (do not type the quotes)
5. At the command prompt type "npm install"  (do not type the quotes)

The software is now installed.

To start the software:
1. Start a windows command prompt by typing "cmd" in the search box a t the bottom of the windows desktop screen (do not type the quotes)
2. In the command prompt window type "cd\laserweb" at the command prompt (do not type the quotes)
3. In the command prompt window type "node server" at the command prompt (do not type the quotes)
4. Start the google Chrome web browser (software is only tested to work with Chrome) 
5. At the top of the Chrome window type "localhost:8000" in the web address bar (do not type the quotes)

You should now see the software in the Chrome browser window.

**Comment by funinthefalls** [comment]
Can you add this to the Readme file?

I am willing to work on documentation and help files if you want.

**Comment by ghost** [comment]
You can either post it as a pull request (in the web github.com,  open readme,  click the edit button. (little pencil)  and apply changes.  Submit as a pull request.  

Or i can give you contribution rights to the repo if you are familiar with git? 

Just a note,  dont download the zip,  make sure you install git instead.  The auto update components of laserweb uses git...  So skipping that,  breaks future work (:

**Comment by funinthefalls** [comment]
The reason I said to use the zip instead of git was because these instructions were posted as a result of a user on the opensource laser group that asked for step by step instructions because he was not that computer savvy. So I figured there was no way someone who needs to have there hand held to install it would be able to install and use Git For Windows. I would not mind having contributor rights for the repository, I have a basic understanging of the Git workflow process, I just don't want to screw anything up by accident.

Date: Fri, 15 Jan 2016 11:56:09 -0800

**Comment by ghost** [comment]
Collaborator status added (:   welcome to the team.  (: 
I love how LaserWeb is becoming community property

**Comment by funinthefalls** [comment]
Thanks for the add Peter. Once LaserW0eb matures (shouldn't be too much longer with the hard work you have been putting in) we should tackle modding Repetier to a laser specific version.

Date: Fri, 15 Jan 2016 20:14:03 -0800

**Comment by ghost** [comment]
(: i was just 5 mins ago loading up Repetier to one of my Evitabot controllers so I can take the plasma for a spin on Monday when the neighbours go to work (wont piss them off by playing on a sunday).  Setting num_extruders to 0 disabled all the temp controls.  One line,  so clean and elegant.  Love that firmware @Repetier is a legend!
