### ISSUE TITLE
Screen shots need updating in repository, screen shots need adding to WIki

### ISSUE THREAD

**Issue by funinthefalls** [openhardwarecoza/LaserWeb#66]
Screen shots are out of date. Will update all screen shots once a week to try and keep them somewhat current.

**Comment by funinthefalls** [comment]
Peter, how do I upload new screen shots to the repository?

**Comment by ghost** [comment]
Replace the existing images in your local. copy,  then do a git add *,  git commit - m "updated screenshots",   git push origin master

**Comment by ghost** [comment]
Oh and for new ones, copy them into the screenshots directory and then add, commit, push
