### ISSUE TITLE
dxf gcode generation

### ISSUE THREAD

**Issue by athulsnair** [openhardwarecoza/LaserWeb#67]
Hi,
I installed the software, but i coudn't genrate gcodes for .dxf files. I am attaching the dxf file generated gcode.
 I tried to install in anotherpc but getting the same result.
This is the gcode that I'm getting
; TOOL OPTIONS
; units: mm
; diameter: 0.1
; passDepth: 3
; step: 1
; rapid: 3000
; plunge: 10000
; cut: undefined
; zClearance: 0
; returnHome: true

; SETTING UNITS TO mm
G21

; SETTING ABSOLUTE POSITIONING
G90
M02

; RETURNING TO 0,0,0 BECAUSE this.tool.returnHome IS SET
G0 F3000 X0 Y0 Z0

I'm using Windows 7 64bit and GRBL
Also I can't control the power,can't scale or move.
Am I the only one having this problem?

![2](https://cloud.githubusercontent.com/assets/16574115/12412894/a86e58da-beb0-11e5-9929-df80fdadef87.png)

(https://github.com/openhardwarecoza/LaserWeb/files/95519/Material.Thickness.docx)
![untitled](https://cloud.githubusercontent.com/assets/16574115/12412853/46e0542e-beb0-11e5-9370-a9ca768da4bd.jpg)

**Comment by ghost** [comment]
This also relates to https://github.com/openhardwarecoza/LaserWeb/issues/42

Please share a link to https://github.com/openhardwarecoza/LaserWeb/issues/42 on your social media and hunt down anyone you know that knows Javascript - we can always use more people to get the development out the door quicker (:

Basically - the current library works only with Polyline DXFs and doesnt support Arcs (so for example dxfs from openscad and sketchup work perfectly) 

The new library we have started integrating can parse and display pretty much any DXF I throw at it (displays it in blue) but doesnt yet generate Gcode.  For each of the three.js draw functions from https://github.com/openhardwarecoza/LaserWeb/blob/master/i/dxf/three-dxf.js#L287 downward - we just need to generate Gcode...  If you read through the original thread, you'd see there are a few people working on it (:

In the meantime, what do you draw in?   Does it have the option to break arcs/circles into polyline segments? And then of course export your files as polylines (not lines)

**Comment by ghost** [comment]
Closing this, rather follow along (and interact please) on issue #42

**Comment by athulsnair** [comment]
The file that you can see in the screenshot is generated using fusion 360.

**Comment by ghost** [comment]
Doesnt matter, same issue.  Set fusion to export polyline dxfs without arcs
or use the builtin cam

**Comment by athulsnair** [comment]
Also the scaling and moving tabs are not working.(I mean even if I scale down object to 50% , there's no change)

**Comment by ghost** [comment]
Listen to what I asked, go read the other thread.  The Blue one is just a debug.  Use a valid polyline DXF and you will see the difference...  (a dark red render from the gcode)

**Comment by ghost** [comment]
Your log will also show the errors.

**Comment by ghost** [comment]
I disabled the blue debug render.  Now you'll see your dxf wont open ANYTHING since its not polyline

**Comment by ghost** [comment]
Test file for you to see:  [polyline-dxf-from-sk.dxf.zip](https://github.com/openhardwarecoza/LaserWeb/files/98824/polyline-dxf-from-sk.dxf.zip)

Heres a plain polyline dxf with no arcs.    Give it a go (:

If you'd like us to support arcs and non-polyline shapes - head over to #42 and help us out (:

**Comment by openhardwarecoza** [comment]
This should also help:  

https://forums.autodesk.com/t5/design-validate-document/export-svg/td-p/5812107

**Comment by ghost** [comment]
I am not a fusion user , but you could give this a try https://apps.autodesk.com/FUSION/en/Detail/HelpDoc?id=appstore.exchange.autodesk.com%3Adxfsplinetopolyline_windows64%3Aen

**Comment by ghost** [comment]
Test example with polyline dxf:

![dxf1](https://cloud.githubusercontent.com/assets/7695323/12474189/bc8f50cc-c021-11e5-9373-d9477e5dc531.png)

And scaled to 50%

![50](https://cloud.githubusercontent.com/assets/7695323/12474193/bfd4a5ca-c021-11e5-95e1-6d57d53cbf0b.png)

**Comment by cojarbi** [comment]
this is what i got with that. Well that was before the latest commit. I got nothing on the screen after commint
<img width="669" alt="screen shot 2016-01-21 at 7 27 01 am" src="https://cloud.githubusercontent.com/assets/16444438/12480454/75aa2b66-c010-11e5-86f9-ddf82c4fc1c9.png">
<img width="438" alt="screen shot 2016-01-21 at 7 27 10 am" src="https://cloud.githubusercontent.com/assets/16444438/12480455/75ab5176-c010-11e5-8677-da78f3b7af32.png">

**Comment by ghost** [comment]
That looks pretty usable?

**Comment by ghost** [comment]
but wait, thats blue not red. Do a git pull first (:

**Comment by cojarbi** [comment]
updated my comment. above
