### ISSUE TITLE
Be able to change settings from GUI

### ISSUE THREAD

**Issue by adeebshihadeh** [openhardwarecoza/LaserWeb#7]

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
Right,  so starting to think of tackling this one. 

I am thinking Nosql would be quickest,  easiest.  Config data is nice and flat.

**Comment by andrewhodel** [comment]
It's already in reprapweb as a json string saved and loaded to a file. 

That's with many options and as it is in memory it is instant, dbs are overrated for control apps. Dbs are for data storage and even then I'd argue to store to files and use the same type code as an index (that's what a db is). 

You can't count on dbs for long. Before long the requirements list will grow unapproachable. 

There are simple in memory or file dbs as well but is it really that hard to just read and write json?

**Comment by openhardwarecoza** [comment]
Aha, then theres even example code for me to work from.  SlOpts?   let me get working on that

**Comment by ghost** [comment]
https://github.com/andrewhodel/reprapweb/blob/master/server.js#L274 (:

**Comment by andrewhodel** [comment]
It's just JavaScript JSON.parse() and Object.stringify(). Object is or contains JSON.

You can prototype any functions to anything.

**Comment by Cinezaster** [comment]
https://www.npmjs.com/package/node-persist
- [x] Is persistent
- [x] writes to a json file
- [x] uses localStorage API style

Never used this but looks promising : https://github.com/louischatriot/nedb and works with electron If you ever want to build it as an application.
This can also store files, nice feature if you want to keep the gcode, svg, dxf files the user uploads/loads.

**Comment by andrewhodel** [comment]
https://github.com/andrewhodel/reprapweb/blob/master/server.js#L274

From line 274 to 321 does the same thing in just 47 lines of code rather than an entire module you have to trust in the future.

**Comment by ghost** [comment]
I kicked off work on this!  Too many new issues starting to depend on having this in place:
-- User customisable laser on, laser off, and Sxxx value configs
-- Custom buttons
-- Git pulls not working when you update the ui.js with new bed size

JSON:
![jsontree](https://cloud.githubusercontent.com/assets/7695323/12489881/4528a740-c07b-11e5-9ee8-739958d8010b.png)

**Comment by cojarbi** [comment]
Would be useful to be able to define the name of the file before downloading the gcode

**Comment by ghost** [comment]
![screenshot from 2016-01-28 17-04-14](https://cloud.githubusercontent.com/assets/7695323/12648139/2d7a2fc2-c5e1-11e5-9891-e009b2b1f719.png)

Status update:

(and dev guide)
1.  The available options are built up from https://github.com/openhardwarecoza/LaserWeb/blob/master/slBaseOpts.js
2.  It gets saved to 'machines' in root of laserweb as json,  loaded on startup, and saved, deleted, edited - by https://github.com/openhardwarecoza/LaserWeb/blob/master/server.js#L531 down to https://github.com/openhardwarecoza/LaserWeb/blob/master/server.js#L627
3.  They get pushed to the frontend, and handled by https://github.com/openhardwarecoza/LaserWeb/blob/master/i/main.js#L150 down to https://github.com/openhardwarecoza/LaserWeb/blob/master/i/main.js#L298

What I am not doing yet is to use https://github.com/openhardwarecoza/LaserWeb/blob/master/i/main.js#L413 to set the variables we need to use elsewhere (start, stop gcode, laser on off and power commands, bed size, etc)

**Comment by ghost** [comment]
Note that this is WORKING in LaserWeb2 and since LaserWeb2 will soon replace LaserWeb1,  if you need this functionality please checkout LaserWeb2 instead
