### ISSUE TITLE
Weird raster render result

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb#72]
Using standard procedure im getting the following result in the raster render and calibration. This is under the latest commit. Not connected to any board
<img width="497" alt="screen shot 2016-01-19 at 7 48 46 am" src="https://cloud.githubusercontent.com/assets/16444438/12419198/802f6a0e-be82-11e5-86c2-e94457314193.png">
<img width="1920" alt="screen shot 2016-01-19 at 7 54 31 am" src="https://cloud.githubusercontent.com/assets/16444438/12419199/80306c1a-be82-11e5-9c9e-836ed8fe0863.png">

**Comment by nathanielstenzel** [comment]
This is my fault for not testing my code and referencing a variable that is not even initialized. I made an adjustment. Please test.

**Comment by nathanielstenzel** [comment]
I confirmed earlier that it is fixed. I still do not have the results for my patch though.
