### ISSUE TITLE
Loosing control in " machine control "

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb#79]
Im loosing the connection to the controller by doing the following:

Start a jog, Pause, Clear Q, Machine control, Jog. The jog is not recognized. The only way to regain control is to stop laserweb from terminal and start it again.

This is the only thing i get on all this from terminal
unpausing queue
unpausing queue
pausing queue

**Comment by ghost** [comment]
I'll test this when my Smoothiebrainz boards come in - too difficult fixing without hardware at hand
