### ISSUE TITLE
Errors in GRBL 9g (jtech)

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb#85]
First some errors on the terminal. I dont think i saw them yersterday. See attached

Also random vertical movements in the middle of lasering. I could not replicated back to back the same movement but in all test the is a vertical one. Attached gcode

Movement with machine control also turn on the laser. Same procedure to shut down

At the end of the run the laser stays On. Only way to shut it down is first M03 and then M05
[grbl error terminal LW.txt](https://github.com/openhardwarecoza/LaserWeb/files/102582/grbl.error.terminal.LW.txt)
[grbl jtech GCODE-LaserWeb (1).gcode.txt](https://github.com/openhardwarecoza/LaserWeb/files/102583/grbl.jtech.GCODE-LaserWeb.1.gcode.txt)

**Comment by cojarbi** [comment]
Here is another gcode. This one seems to skip dots in the same line and then does them on the return.
[GRBL skips dots.gcode.TXT](https://github.com/openhardwarecoza/LaserWeb/files/102602/GRBL.skips.dots.gcode.TXT)

**Comment by cojarbi** [comment]
Another one. Long Y movement towerds the end of the code. Also a lot of hiccups during line codes ( stops for less than a second )
[LADY long vertical movement GCODE-LaserWeb (1).gcode.txt](https://github.com/openhardwarecoza/LaserWeb/files/102607/LADY.long.vertical.movement.GCODE-LaserWeb.1.gcode.txt)

**Comment by ghost** [comment]
@nathanielstenzel  (;  - I am too busy at work this week :(

**Comment by funinthefalls** [comment]
I wondered where you went, I am used to seeing you spending tons more time working on this project. Don't worry about the schematic for my project, I will buckle down and relearn how to use eagle. While you are busy at work I will try to finish up the Wiki for LaserWeb, I am about 95% complete now.

**Comment by nathanielstenzel** [comment]
When did this start happening and when was your last update before that?

**Comment by cojarbi** [comment]
I started with GRBL yesterday so I think there have been 2 commits after that.  It's started since I connected yesterday. 

Ariel Yahni

**Comment by ghost** [comment]
@funinthefalls yeah that festive slowdown is over!  Work sits in piles in my desk :(

**Comment by cojarbi** [comment]
I have made a mistake in the title, so all this issues are for 0.9g modified by Jtech

**Comment by ghost** [comment]
#88  - see Stock Grbl (;

**Comment by cojarbi** [comment]
Stock grbl. 9j uses power range 0-10000 so 9g should also use the same. That's why jtech compiled it differently

**Comment by athulsnair** [comment]
@cojarbi not only that , after reading through shapeoko forum this is what I got , grbl flushes the buffer before changing spindle speed. So when there is a spindle speed change , grbl assumes that you are using a milling machine and it will not accelerate (it stops ) so that spindle can achieve new speed i.e., machine will not accelerate smoothly through spindle speed changes. 
In modified versions this is avoided.
[http://www.shapeoko.com/forum/viewtopic.php?f=3&t=6970&start=10](url)

**Comment by ghost** [comment]
Right, so while I was at work, looks like you two made some progress.

Do we need to add the m3/m5 to raster still?  Or is grbl now honoring the power level change as enough (the less serial data we need to send  the better)

More importantly - we need to finish #7 - then you can configure your own machine profile from the UI (go see screenshot at bottom of the thread on issue no 7 I posted a few mins ago) without any coding in the backend...

**Comment by cojarbi** [comment]
Today i flashed 0.9j master and modified it to S255. Since laserweb is not seding M03 commands the laser does not turn on.
Then changed to 0.9g Jtech and it works even though no M03 comands are present on the gcode but there are some random laser on/off and random movements

**Comment by athulsnair** [comment]
@cojarbi Edit the gcode(add m3 at the beining and m5 at the end) that's what i'm doing

**Comment by athulsnair** [comment]
@openhardwarecoza  grbl 0.9j requires m3 and m5

**Comment by openhardwarecoza** [comment]
I am simply drowing in work

Open laserraster.js and add the code to each move

Send me a pull request after testing...

**Comment by ghost** [comment]
In https://github.com/openhardwarecoza/LaserWeb/blob/master/i/raster/laserraster.js#L223

```
if (this.config.useVariableSpeed) {
          this.result += 'G1 X{0} Y{1} S{2} F{3}\n'.format(posx, gcodey, lastIntensity, speed);
        } else {
          this.result += 'G1 X{0} Y{1} S{2}\n'.format(posx, gcodey, lastIntensity);
        }
```

Change to 

```
if (this.config.useVariableSpeed) {
           if (this.config.firmware.indexOf('Grbl') == 0) {
                 this.result += 'M3\n';
          }
          this.result += 'G1 X{0} Y{1} S{2} F{3}\n'.format(posx, gcodey, lastIntensity, speed);
           if (this.config.firmware.indexOf('Grbl') == 0) {
                 this.result += 'M5\n';
          }
        } else {
           if (this.config.firmware.indexOf('Grbl') == 0) {
                 this.result += 'M3\n';
          }
          this.result += 'G1 X{0} Y{1} S{2}\n'.format(posx, gcodey, lastIntensity);
           if (this.config.firmware.indexOf('Grbl') == 0) {
                 this.result += 'M5\n';
          }
        }
```

**Comment by ghost** [comment]
Pushed - do a git pull update and let me know!

**Comment by athulsnair** [comment]
There're m3 and  m5 commands and laser output, but noticed several unwanted movements (even though machine comes back to the required position) and there was a long pause at a time (I didn't do full engraving, so don't know if there's more than one).

I also like to mention one more thing,I generated a raster gcode using laserweb , downloaded the generated gcode, manually inserted M3 and M5 command and run it by laserweb, later I run the same gcode using chilipeppr and result was quite different from what I got from laserweb.
In laserweb there was lots of gaps ( there's wasn't laser sometimes) and error messages were
   invalid gcode ID:24 and
   bad number format

Top one in the image is from chilipeppr and bottom one from laserweb
![img_20160129_154146492](https://cloud.githubusercontent.com/assets/16574115/12675895/9f6708bc-c6b3-11e5-8fc5-a2a9c07ba88f.jpg)

I'm also attaching modified gcode(manually inserted m3 and m5) and gcode I got after new fix (raster with M3 and M5) and png image
[manually inserted M3 and M5.docx](https://github.com/openhardwarecoza/LaserWeb/files/109741/manually.inserted.M3.and.M5.docx)
[raster with m3 and m5.docx](https://github.com/openhardwarecoza/LaserWeb/files/109742/raster.with.m3.and.m5.docx)
![ir_attachment_658](https://cloud.githubusercontent.com/assets/16574115/12676387/e85746fa-c6b7-11e5-877b-a91e50662c93.png)

**Comment by ghost** [comment]
Was SPJS shutdown while you were testing with Laserweb? Those unknown gcode messages pop up when something else talks to the controller at the same time (; 

ID:24 doesnt appear in your gcode nor in grbls responses, so looks like something else was talking to that port too

**Comment by ghost** [comment]
As a sidenote, I wouldnt mind someone working on https://github.com/openhardwarecoza/LaserWeb/issues/21 - so if you feel the serial comms could be better, open a seperate thread (if if we have to use SPJS too (;  -)

**Comment by ghost** [comment]
Mind you, looking back at post one, cojarbi also had a ID2x error in his log... very weird, where is it coming from?

**Comment by ghost** [comment]
Ok, let me guess. you are both on Mac, and instead of seeing the nicely colored lines, your Jobsware chokes on the ANSI code and prints things like ID24 instead of coloring it :/

It should look like this:  
![colored](https://cloud.githubusercontent.com/assets/7695323/12676578/274a1250-c69c-11e5-9a6c-d9435a08d1bc.png)

And yes yes, I know I shouldnt hate on mac.,  But come on.... lol
ANSI color codes worked on my first 486dx with a CGA graphics adapter back in 1993!

**Comment by ghost** [comment]
Gents, fix your Macs:  See http://stackoverflow.com/questions/29364326/how-to-use-chalk-terminal-string-styling-done-right so we can get better logs out thats actually usable

**Comment by ghost** [comment]
Continuing my one sided rant:

Your error says it complains about Number Format
Check if the S values match what grbl expects?  (decimals etc?)

**Comment by ghost** [comment]
The docx's you uploaded (Why, theres a big SAVE GCODE button?) shows the m3/m5s in the right spots now.  So i think (to avoid convulated confusing issue threads) we close this one and handle the serial issues (since the exported file runs fine in another host) seperately.  I'll open a new issue with debug instructions
Since thats not grbl specific... (Chirag had a similar issue with Marlin)

NB: Log seperate issues, for seperate problems (;

**Comment by cojarbi** [comment]
@athulsnair and I have something else common I believe. We bough tried chillippeper and now I think that the json serial server could be the issue. I did went over their git asking how to uninstall it completely but the response was that if it's off then should not interfere with anything

**Comment by ghost** [comment]
kill the process... then its gone (delete the executable if you are scared it is running)

**Comment by cojarbi** [comment]
I killed the MF with a laser :) 

Just thinking what you said about something else talking in there

Ariel Yahni

**Comment by athulsnair** [comment]
@openhardwarecoza  I'm windows 10 user not MAC           

And I don't know anything about coding .I'm trying to modify my X carve in to  a laser cutter and testing it by using laser web.
Are you saying JSON server that I use for the chilipeppr is communicating with the serial port ?? and that's why I'm getting all the errors??

**Comment by ghost** [comment]
Its possible,  but refer the other issue.. We have a few prople working on this now.  Sit tight for a day or two,  we'll fix the serial bug soon
