### ISSUE TITLE
Object packing via genetic algorithm

### ISSUE THREAD

**Issue by mostley** [openhardwarecoza/LaserWeb#86]
Basically the possibility to load a file with mutliple objects or multiple files and then pack the contained objects as closely together as possible (in a given timeframe)
implementation: https://github.com/Jack000/SVGnest

**Comment by ghost** [comment]
Already discussed here https://plus.google.com/+ArthurWolf/posts/eVxYxnQCiHp 
We even had SVGnest's author join that discussion.  

Go read the comments (:
