### ISSUE TITLE
Support for Wifi SD cards (Flashair, etc)  and also for HTTP post SD card upload on Smoothie

### ISSUE THREAD

**Issue by ghost** [openhardwarecoza/LaserWeb#87]
An idea from John over on the Hackaday Comments Threads:
http://hackaday.com/2016/01/26/stop-driving-laser-cutters-with-3d-printer-software/#comment-2898642

Use a Wifi SD installed on the controller.

I think I'll order one and start playing to add a "push to SD" button in Laserweb that uploads it to these wifi SD cards - that would be a win!

**Comment by ghost** [comment]
https://github.com/openhardwarecoza/LaserWeb/wiki/SPONSORS -  feel like donating some hardware? 
Or if you have more info how we can do the upload using a Ajax POST?

**Comment by funinthefalls** [comment]
Let me check my Wanhoa users group, if I remember correctly, someone managed to make this idea work very easily with a 3dprinter. Hopefully I can find the thread.

**Comment by funinthefalls** [comment]
https://flashair-developers.com/en/documents/tutorials/advanced/2/
