### ISSUE TITLE
Laser on while connecting

### ISSUE THREAD

**Issue by athulsnair** [openhardwarecoza/LaserWeb#88]
Laser is ON for a second while starting laserWeb.

Also can you add m3 and m5 commands while generating gcodes for raster.

**Comment by ghost** [comment]
If your laser is on during starting it means your hardware has floating pins!   Add pulldown resistors! 
(when we connect, it resets the board, while firmware is not holding the pins in a valid state, they float, which may be enough to trigger your laser)

(Give me more details on what hardware and firmware you are using if you need more help... )

Regarding m3/m5 - same - what firmware are you using/ Can't help you out if you dont log detailed issues (I can't add the if indexof.firmware code without knowing which firmware you have that needs M3/m5? (Lasaurgrbl, marlin, smoothie and the grbl jtech forks all use g0/g1)

**Comment by athulsnair** [comment]
I'm using GRBL 0.9j with Gshield (pwm from 0-255)

**Comment by ghost** [comment]
Ok, so for 0.9J - refer to the duplicate bug already logged: https://github.com/openhardwarecoza/LaserWeb/issues/85

For the reset issue - add pulldown resistors to gnd on your laser out pins (or keep laser power off until ready to cut)

**Comment by athulsnair** [comment]
What I understand from reading that post is it uses modified version of grbl and I'm using original version and I don't have any problem with cutting by uploading a dxf file.(it has m3 and m5 commands and S parameter from 0-255 , that's enough form me).

**Comment by ghost** [comment]
Ok,  will take a look shortly.

**Comment by cojarbi** [comment]
@athulsnair are you sure u are using Master. 9j and it's power range is S0-255? I'm sure I've tried that and it's 0-10000 based on spindle rpm

**Comment by cojarbi** [comment]
https://github.com/grbl/grbl/issues/892

**Comment by athulsnair** [comment]
@cojarbi
 I changed the config.h file in grbl master .
look for #define_max_spindle_rpm in config.h file,by default it's 1000rpm, change it to 255 so that S255 comment  will give you 5V on pin 11 (variable spindle should be enabled)
Check issue #877 in grbl

**Comment by athulsnair** [comment]
[](https://github.com/grbl/grbl/issues/877#issuecomment-170151182)

**Comment by ghost** [comment]
M3+m5 added https://github.com/openhardwarecoza/LaserWeb/commit/093233c910843aed856eb4e84078f67ee04b9f31
