### ISSUE TITLE
Adding on the fly power and speed adjustments

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb#89]
After creating the raster code ( which takes time ) settings for power and speed could be off, so an adjustment on speed and power could save you from starting all over again.  This could be very useful for the Calibration widget.

**Comment by Cinezaster** [comment]
+1 I think this is indeed a clever idea. 
Parsing the image to g-code paths is the hardes part.
Changing g-code parameters is way easier. Changing speed and laser power is not that difficult if you have all the movements. 
If the g-code is handled as a big array of objects, this would not be that hard to implement.

**Comment by ghost** [comment]
Good idea...  PR welcomed!

**Comment by ghost** [comment]
LaserWeb1 is retired, see https://github.com/openhardwarecoza/LaserWeb3
