### ISSUE TITLE
Won't start on OS X

### ISSUE THREAD

**Issue by adeebshihadeh** [openhardwarecoza/LaserWeb#9]
I'm getting an error because LaserWeb tries to initially connect to the bluetooth serial port on os x. This is when I don't have the laser plugged in. 

```
MacBook-Pro:LaserWeb quillford$ node server.js
Got error: connect ECONNREFUSED not enabling webcam
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Cannot open /dev/cu.Bluetooth-Modem
    at Error (native)
```

**Comment by ghost** [comment]
I dont own a mac to test on, but I think this belongs upstream, log an issue on https://github.com/voodootikigod/node-serialport

**Comment by adeebshihadeh** [comment]
I think it's because LaserWeb tries to automatically connect to the available ports. Having the user select the port would probably fix the issue.

**Comment by ghost** [comment]
If thats the case, it would affect GrblWeb and ReprapWeb too.  @andrewhodel ?

**Comment by andrewhodel** [comment]
Most people are using the rpi images I'd imagine, if they are building it from source to run on os x surely they can just type in the port name they want to use in the code.  Or just use the tty as a file like it's supposed to be.... ehrm... windows.
