### ISSUE TITLE
Test run before laser job

### ISSUE THREAD

**Issue by cojarbi** [openhardwarecoza/LaserWeb#90]
This will help with placing the material correctly and verify it's placement. Would run at higher speed with low power. 
This could be done as a temporary duplicate of the actual job (specially for raster that takes to much time). Settings for this could be an additional option in user preferences. Selection toggle on raster and other jobs types widgets to enable this feature for that specific job.

**Comment by ghost** [comment]
Have you tried the Draw Bounding Box button?  That moves on the max/min positions of the job -  works for me
