### ISSUE TITLE
Smoothie Rastering Error

### ISSUE THREAD

**Issue by saskia-fabcreator** [openhardwarecoza/LaserWeb#99]
Am trying to raster engrave using smoothieboard, it worked happily before the weekend but coming up with an error after update:

Application Error: ReferenceError: intensity is not defined (from http://145.107.25.149:8000/raster/laserraster.js line 209

```
207   var speed = this.config.feedRate;
208   if (lastGrey != this.grayLevel) {
209   intensity = this.figureIntensity();
210   speed = this.figureSpeed(lastGrey);
211   lastGrey = this.grayLevel;
```

**Comment by cojarbi** [comment]
What kind of laser r u using?

**Comment by saskia-fabcreator** [comment]
40W self built smoothieboard controlled, connected to laptop

**Comment by ghost** [comment]
Just tested, on a smoothieboard, and working fine for me

Do a git pull if you havent yet  (theres a few commits a day so probably already ahead of you)

**Comment by saskia-fabcreator** [comment]
Yes, it seems to be happy again
